<?php

namespace Database\Seeders;

use App\Models\Employee;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NonCoopMember extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $employees = [
            ['lastname'=>'ADALIN','firstname'=>'RC','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'AGUILAR','firstname'=>'RO','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'ALAMBAN','firstname'=>'AP','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'APAT','firstname'=>'JM','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'BAANG','firstname'=>'GA','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'BAGAYAS','firstname'=>'RH','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'BALENDEZ','firstname'=>'EP','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'BARBADILLO','firstname'=>'AA','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'BASERGO','firstname'=>'RC','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'BELMONTE','firstname'=>'ER','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'BELMONTE','firstname'=>'PT','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'BERNALDEZ','firstname'=>'J','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'CACHO','firstname'=>'JC','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'CARPENTERO','firstname'=>'VG','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'CASTRO','firstname'=>'TS','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'CAVITE','firstname'=>'FS','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'DACUT','firstname'=>'EG','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'DAJANG','firstname'=>'MN','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'DIESTO','firstname'=>'','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'DIEZ','firstname'=>'TD','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'EDRALIN','firstname'=>'EO','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'EDRALIN','firstname'=>'MT','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'EDRALIN','firstname'=>'SA','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'GAMBOA','firstname'=>'HL','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'GARGUENA','firstname'=>'IH','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'GARILAO','firstname'=>'SG','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'IBANEZ','firstname'=>'JS','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'INIHAO','firstname'=>'MG','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'LABO','firstname'=>'MD','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'LAGUERTA','firstname'=>'MR','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'LANTACA','firstname'=>'RS','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'LAUREL','firstname'=>'JN','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'LIGTAO','firstname'=>'JC','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'LIM','firstname'=>'JM','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'LOZADA','firstname'=>'VM','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'MADARANG','firstname'=>'BN','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'MAGDALE','firstname'=>'JE','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'MAGDALE','firstname'=>'MG','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'MAGLASANG','firstname'=>'JM','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'MALACAMAN','firstname'=>'VL','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'MANDA','firstname'=>'PI','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'MAR','firstname'=>'AL','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'NAMOC','firstname'=>'EB','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'NAMUAG','firstname'=>'AT','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'PADUA','firstname'=>'LB','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'PAGARAN','firstname'=>'LJ','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'PALMA','firstname'=>'BB','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'PALUGA','firstname'=>'AB','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'PALUGA','firstname'=>'MD','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'RAMIRO','firstname'=>'RL','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'REMOTIGUE','firstname'=>'ME','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'ROMO','firstname'=>'JM','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'ROQUE','firstname'=>'PA','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'SANCHEZ','firstname'=>'VT','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'SANTOS','firstname'=>'RR','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'SAYON','firstname'=>'PS','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'SEDAYA','firstname'=>'CS','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'SICAT','firstname'=>'E','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'TEJANO','firstname'=>'MC','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'TOLITOL','firstname'=>'NJ','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'TOMAS','firstname'=>'ET','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'TRIBUNAL','firstname'=>'EA','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'VERDEFLOR','firstname'=>'DS','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'VIERNES','firstname'=>'RA','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'VILLACERAN','firstname'=>'BC','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
            ['lastname'=>'VISMANOS','firstname'=>'RS','chapanumber'=>'','middlename'=>'','extension'=>'','birthdate'=>'2000-01-01','civilstatus'=>'','sex'=>'','religion'=>'','department'=>'','position'=>'','employmentdate'=>'2000-01-01','phonenumber'=>'','educationalattainment'=>'','estimatedannualgross'=>0,'tin'=>'','prahouseno'=>'','prabuildingstreet'=>'','prasubdivision'=>'','prabarangay'=>'','pramun'=>'','praprov'=>'','prazipcode'=>'','peahouseno'=>'','peabuildingstreet'=>'','peasubdivision'=>'','peabarangay'=>'','peamun'=>'','peaprov'=>'','peazipcode'=>'','pmailadd'=>'','email'=>'','fbaccount'=>'','ispinecoopmem'=>0,'dateofmembership'=>'2022-01-01','pwdid'=>'','ispersonwithdisability'=>0,'status'=>'Active'],
        ];

        foreach($employees as $employee){
            DB::table('employees')->insert([
                'lastname' => $employee['lastname'],
                'firstname' => $employee['firstname'],
                'middlename' => $employee['middlename'],
                'extension' => $employee['extension'],
                'birthdate' => $employee['birthdate'],
                'civilstatus' => $employee['civilstatus'],
                'sex' => $employee['sex'],
                'religion' => $employee['religion'],
                'department' => $employee['department'],
                'position' => $employee['position'],
                'employmentdate' => $employee['employmentdate'],
                'phonenumber' => $employee['phonenumber'],
                'educationalattainment' => $employee['educationalattainment'],
                'estimatedannualgross' => $employee['estimatedannualgross'],
                'tin' => $employee['tin'],
                'prahouseno' => $employee['prahouseno'],
                'prabuildingstreet' => $employee['prabuildingstreet'],
                'prasubdivision' => $employee['prasubdivision'],
                'prabarangay' => $employee['prabarangay'],
                'pramun' => $employee['pramun'],
                'praprov' => $employee['praprov'],
                'prazipcode' => $employee['prazipcode'],
                'peahouseno' => $employee['peahouseno'],
                'peabuildingstreet' => $employee['peabuildingstreet'],
                'peasubdivision' => $employee['peasubdivision'],
                'peabarangay' => $employee['peabarangay'],
                'peamun' => $employee['peamun'],
                'peaprov' => $employee['peaprov'],
                'peazipcode' => $employee['peazipcode'],
                'pmailadd' => $employee['pmailadd'],
                'email' => $employee['email'],
                'fbaccount' => $employee['fbaccount'],
                'ispinecoopmem' => $employee['ispinecoopmem'],
                'dateofmembership' => $employee['dateofmembership'],
                'pwdid' => $employee['pwdid'],
                'ispersonwithdisability' => $employee['ispersonwithdisability'],
                'chapanumber' => $employee['chapanumber'],
                'status' => $employee['status'],
            ]);
        }

        $employees = Employee::where('ispinecoopmem',0)->get();

        foreach($employees as $employee){

            DB::table('accounts')->insert([
                'accounttype_id' => 2,
                'employee_id' => $employee->id,
                'date_opened' => '2021-12-01',
            ]);

        }
    }
}
